#!/bin/sh

# Check for git and a git repo.
LOCAL=$(if head=`git rev-parse --verify HEAD 2>/dev/null`; then
	# Do we have an untagged version?
	if git name-rev --tags HEAD | grep -E '^HEAD[[:space:]]+(.*~[0-9]*|undefined)$' > /dev/null; then
		printf '%s%s' -g `echo "$head" | cut -c1-8`
	fi

	# Are there uncommitted changes?
	if git diff-index HEAD | read dummy; then
		printf '%s' -dirty
	fi
fi)

cat <<EOF
package org.ecmdroid;

/* Generated Class */
public interface VCS
{
	public static final String LOCAL_VERSION = "$LOCAL";
}
EOF
